{{- if and .Values.metrics.enabled .Values.metrics.podMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ include "retina.fullname" . }}
  namespace: {{ ternary .Values.metrics.podMonitor.namespace .Values.namespace (not (empty .Values.metrics.podMonitor.namespace)) }}
  labels:
    k8s-app: {{ include "retina.name" . }}
    {{- if .Values.metrics.podMonitor.additionalLabels }}
    {{- .Values.metrics.podMonitor.additionalLabels | nindent 4 }}
    {{- end }}
spec:
  podMetricsEndpoints:
    - port: http
      path: /metrics
      {{- if .Values.metrics.podMonitor.interval }}
      interval: {{ .Values.metrics.podMonitor.interval }}
      {{- end }}
      {{- if .Values.metrics.podMonitor.scrapeTimeout }}
      scrapeTimeout: {{ .Values.metrics.podMonitor.scrapeTimeout }}
      {{- end }}
      {{- if .Values.metrics.podMonitor.scheme }}
      scheme: {{ .Values.metrics.podMonitor.scheme }}
      {{- end }}
      {{- if .Values.metrics.podMonitor.tlsConfig }}
      tlsConfig: {{- .Values.metrics.podMonitor.tlsConfig | nindent 8 }}
      {{- end }}
      {{- if .Values.metrics.podMonitor.relabelings }}
      relabelings: 
      {{- .Values.metrics.podMonitor.relabelings | nindent 8 }}
      {{- end }}
  namespaceSelector:
    matchNames:
      - {{ .Values.namespace }}
  selector:
    matchLabels:
      app: {{ include "retina.name" . }}
{{- end }}
